# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voide/modules/llm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17voide/modules/llm.proto\x12\x14voide.modules.llm.v1\"o\n\nParamValue\x12\x16\n\x0cstring_value\x18\x01 \x01(\tH\x00\x12\x16\n\x0c\x64ouble_value\x18\x02 \x01(\x01H\x00\x12\x13\n\tint_value\x18\x03 \x01(\x03H\x00\x12\x14\n\nbool_value\x18\x04 \x01(\x08H\x00\x42\x06\n\x04kind\"\xa2\x01\n\tPromptMsg\x12\x32\n\x04role\x18\x01 \x01(\x0e\x32$.voide.modules.llm.v1.PromptMsg.Role\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"P\n\x04Role\x12\x14\n\x10ROLE_UNSPECIFIED\x10\x00\x12\x0f\n\x0bROLE_SYSTEM\x10\x01\x12\r\n\tROLE_USER\x10\x02\x12\x12\n\x0eROLE_ASSISTANT\x10\x03\"\xa8\x02\n\tLLMConfig\x12\x0f\n\x07\x61\x64\x61pter\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x13\n\x0btemperature\x18\x03 \x01(\x01\x12\x12\n\nmax_tokens\x18\x04 \x01(\x05\x12\x0f\n\x07runtime\x18\x05 \x01(\t\x12\x30\n\x07prompts\x18\x06 \x03(\x0b\x32\x1f.voide.modules.llm.v1.PromptMsg\x12;\n\x06params\x18\x07 \x03(\x0b\x32+.voide.modules.llm.v1.LLMConfig.ParamsEntry\x1aO\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .voide.modules.llm.v1.ParamValue:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voide.modules.llm_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LLMCONFIG_PARAMSENTRY._options = None
  _LLMCONFIG_PARAMSENTRY._serialized_options = b'8\001'
  _PARAMVALUE._serialized_start=49
  _PARAMVALUE._serialized_end=160
  _PROMPTMSG._serialized_start=163
  _PROMPTMSG._serialized_end=325
  _PROMPTMSG_ROLE._serialized_start=245
  _PROMPTMSG_ROLE._serialized_end=325
  _LLMCONFIG._serialized_start=328
  _LLMCONFIG._serialized_end=624
  _LLMCONFIG_PARAMSENTRY._serialized_start=545
  _LLMCONFIG_PARAMSENTRY._serialized_end=624
# @@protoc_insertion_point(module_scope)
