# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voide/v1/flow.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13voide/v1/flow.proto\x12\x08voide.v1\"\x18\n\x08UserText\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1a\n\nPromptText\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x17\n\x07LLMText\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x17\n\x07\x41nyBlob\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"#\n\x04Port\x12\x0c\n\x04port\x18\x01 \x01(\t\x12\r\n\x05types\x18\x02 \x03(\t\"&\n\x08NodePort\x12\x0c\n\x04node\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"|\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0bparams_json\x18\x04 \x01(\t\x12\x1a\n\x02in\x18\x05 \x03(\x0b\x32\x0e.voide.v1.Port\x12\x1b\n\x03out\x18\x06 \x03(\x0b\x32\x0e.voide.v1.Port\"q\n\x04\x45\x64ge\x12\n\n\x02id\x18\x01 \x01(\t\x12 \n\x04\x66rom\x18\x02 \x01(\x0b\x32\x12.voide.v1.NodePort\x12\x1e\n\x02to\x18\x03 \x01(\x0b\x32\x12.voide.v1.NodePort\x12\r\n\x05label\x18\x04 \x01(\t\x12\x0c\n\x04type\x18\x05 \x01(\t\"a\n\x04\x46low\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x1d\n\x05nodes\x18\x03 \x03(\x0b\x32\x0e.voide.v1.Node\x12\x1d\n\x05\x65\x64ges\x18\x04 \x03(\x0b\x32\x0e.voide.v1.Edgeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voide.v1.flow_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERTEXT._serialized_start=33
  _USERTEXT._serialized_end=57
  _PROMPTTEXT._serialized_start=59
  _PROMPTTEXT._serialized_end=85
  _LLMTEXT._serialized_start=87
  _LLMTEXT._serialized_end=110
  _ANYBLOB._serialized_start=112
  _ANYBLOB._serialized_end=135
  _PORT._serialized_start=137
  _PORT._serialized_end=172
  _NODEPORT._serialized_start=174
  _NODEPORT._serialized_end=212
  _NODE._serialized_start=214
  _NODE._serialized_end=338
  _EDGE._serialized_start=340
  _EDGE._serialized_end=453
  _FLOW._serialized_start=455
  _FLOW._serialized_end=552
# @@protoc_insertion_point(module_scope)
